export const siteConfig = {
	name: "app-acoso-callejero",
	url: "https://app-acoso-callejero.colidevs.com",
	ogImage: "https://app-acoso-callejero.colidevs.com/og.jpg",
	description: "app-acoso-callejero generated by create-coliapp",
	links: {
		instagram: "https://instagram.com/colidevs",
	},
};

export type SiteConfig = typeof siteConfig;
